version: '3.9'

services:
  api:
    container_name: education-api
    build: .
    command: bash -c "python manage.py migrate && python /usr/src/api/manage.py runserver 0.0.0.0:8000 && ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]"
    volumes:
      - .:/usr/src/api/
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
#    env_file:
#      - ./EducationPlatform/env.dev
    depends_on:
      - mysql_db
      - redis

  mysql_db:
    container_name: education-mysql-db
    image: mysql:8.0.31
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: platform
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE_HOST: mysql_db
    restart: always

  redis:
    image: redis:7.0.5-alpine

  celery:
    build: .
    command: celery -A EducationPlatform worker --pool=solo -l INFO
    volumes:
      - .:/usr/src/api
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  celery_beat:
    build: .
    command: celery -A EducationPlatform beat -l INFO
    volumes:
      - .:/usr/src/api
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  flower:
    build: .
    command: celery --broker=redis://redis:6379 flower --loglevel=INFO --port=9090
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - .:/usr/src/api
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - celery
      - celery_beat

volumes:
  mysql_data: