# Generated by Django 4.1.1 on 2022-09-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_testtask_testoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
    ]
