# Generated by Django 4.1.1 on 2022-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_lesson_position_alter_theme_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиция'),
        ),
    ]
