# Generated by Django 4.1.1 on 2022-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_category_courses_alter_task_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default='fweqfqw', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
