# Generated by Django 4.1.1 on 2022-09-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_lesson_position_alter_theme_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
    ]
