# Generated by Django 4.1.1 on 2022-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_course_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=False, upload_to='course/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
