# Generated by Django 4.1.1 on 2022-09-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
    ]
