# Generated by Django 4.1.1 on 2023-01-19 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0010_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Курсы', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
