# Generated by Django 4.1.1 on 2023-01-28 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course/Ruby.png', upload_to='course/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Позиция'),
        ),
    ]
