# Generated by Django 4.1.1 on 2023-02-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_alter_course_image_alter_course_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.theme', verbose_name='Тема'),
        ),
    ]
