# Generated by Django 4.1.1 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_alter_lesson_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='course/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
