# Generated by Django 4.1.1 on 2023-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course/No_image_available.svg.png', upload_to='course/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
