# Generated by Django 4.1.1 on 2023-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
