# Generated by Django 4.1.1 on 2022-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_courses_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='fffwqefwe', max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
