# Generated by Django 4.1.1 on 2022-10-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_image_alter_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
